a = input('Digite algo: ')
print('O tipo primitivo desse valor e:', type(a))
print('So comtém espaços? ', a.isspace())
print('E um número ? ', a.isnumeric())
print('E um alfabelto ? ', a.isalpha())
print('E um alfanúmerico ? ', a.isalnum())
print('Está em maiúsculas ? ', a.isupper())
print('Está em minúsculas ? ', a.islower())
print('Está capitalizada ? ', a.istitle())
